name: Dev Deployment

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  
jobs:
  deploy:
    uses: SpurthiHiremath/GithubActions_ReusableWorkflow/.github/workflows/reusable.yml@main
    with:
      environment: dev
